version: '3.8'

services:
  backend-api:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: uvicorn main:app --host 0.0.0.0 --port 8080  --reload
    env_file: ".env_example"
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file: ".env_example"